#!/bin/bash
CMAKE_BUILD_TYPE=debug
if [ $# -gt 0 ] ; then
	CMAKE_BUILD_TYPE=$1
fi
ANDROID_ABI=armeabi
ANDROID_NATIVE_API_LEVEL=android-20
ANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.8
LIBRARY_OUTPUT_PATH_ROOT=`pwd`
ANDROID_STL=gnustl_static

cmake \
	-DCMAKE_TOOLCHAIN_FILE=`dirname $0`/toolchain/android.toolchain.cmake \
	-DANDROID_NDK=$ANDROID_NDK \
	-DANDROID_SDK=$ANDROID_SDK \
	-DANDROID_ABI=$ANDROID_ABI \
	-DANDROID_NATIVE_API_LEVEL=$ANDROID_NATIVE_API_LEVEL \
	-DANDROID_TOOLCHAIN_NAME=$ANDROID_TOOLCHAIN_NAME \
	-DLIBRARY_OUTPUT_PATH_ROOT=$LIBRARY_OUTPUT_PATH_ROOT \
	-DANDROID_STL=$ANDROID_STL \
	-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
	-DANDROID_NDK_HOST_X64=1 \
	`dirname $0`
